# This is a workflow to build, flash and test firmware.
name: Main workflow

# Controls when the action will run.
on:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-flash-test:
    name: build-flash-test
    runs-on: self-hosted

    strategy:
      fail-fast: false

    env:
      PORT: /dev/ttyUSB0
      BAUDRATE: 115200
      TIMEOUT: 60

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Import project into CCS
        run: make import
      # Calls the makefile for compiling and building the project using the CCS
      - name: make
        run: make
      - name: Flashes the program into the board using Uniflash
        run: make flash
      # Calls the check-devices to echo the USB devices physically connected to the 'runner computer'
      - name: Check connected devices
        run: .github/workflows/./check-devices.sh
      # Calls the uart-terminal script to start monitoring the UART port and report the success/fail criterium
      - name: Run python monitoring script
        run: python3 .github/workflows/uart-terminal-continuous.py $PORT $BAUDRATE $TIMEOUT
